#+-- Plugin RP par stan1712 (stan1712.fr) --+
#+-- Traducteurs : stan1712 (French) | stan1712 (English) | legaming04 (Italian) | Starsaaa (Chinese) | ErHak_ (German) --+

#Version du plugin, il ne faut pas la changer !
Version: "Version 3.9.8-1.0b"

#Modifiez le prefix ici
Prefix: "SeriousRP"

#Messages affichés lors du /seriousrp help
HelpMsg:
  Dsrtp: "Pouvoir se téléporter aléatoirement"
  DTown: "Permet de se téléporter dans la ville"
  DTownSet: "Permet de définir le point de spawn de la ville"
  DTownWhere: "Permet de savoir ou se trouve la ville"
  DPhone: "Affiche le menu du telephone"
  
  DRevive: "Permet de réanimer un joueur"
  DMedInfo: "Permet de connaître les statistiques d'un joueur"
  
  DHelp: "Affiche l'aide"
  DVersion: "Connaître la version du plugin"
  
#Modules du plugin
NoModule: "Le module n'est pas actif."
CustomRecipes: true
RPDeath: false
Medics: true
TownSystem: true
RPMobile: true

#Messages des medics
Medic:
  Revive: "&aVous avez bien reanime le joueur"
  Error: "&cn'est pas en ligne ou vous avez mal orthographie son pseudo !"
  NoNeed: "&cLe joueur n'a pas besoin de se faire réanimer"
MedInfo:
  Health: "Vie :"
  Hearts: "coeurs"
  Food: "Nourriture :"
  Coordinates: "est en :"
  Effects: "Effets"

#Menu du téléphone
Phone:
  LorePhone1: "&9Voici votre téléphone"
  LorePhone2: "&9Clic droit pour l'ouvrir"
  LorePhone3: "&6Propriétaire :"

  Answer: "&aDécrocher"
  HangUp: "&cRaccrocher"
  Shutdown: "&cEteindre"
  
  You: "&aOui, c'est vous, vous êtes beau non ?"
  Music: "&cBientôt..."

  GoToTown: "&aDirection : Ville"
  YourNumber: "&cBientôt..."

#Différents messages du plugin
Teleports:
  GoToTown: "Vous avez été téléporté dans la ville"
  SetTown: "Vous avez défini le spawn de la ville"
  TownWhere: "Le spawn de la ville se trouve en :"

RandomTeleport: "Téléportation à des milliers de blocs !"

Help: "Besoin d'aide ? Tapez /seriousrp help"
VersionHelp: "Version du plugin ? Tapez /seriousrp version"
DiscordHelp: "Rejoignez notre discord ! /seriousrp discord"
Discord: "Notre discord : https://discord.gg/DkQSQa7"

NoPerms: "Vous n'avez pas la permission !"

Locations:
  Town:
    x: 0
    y: 0
    z: 0
    WorldName: world