name: SeriousRP
version: 3.9.8-4.2b
author: stan1712
website: http://www.stan1712.fr
main: fr.stan1712.srp.Main
commands:
 seriousrp:
  description: Show the main menu
  usage: /seriousrp
  permission: seriousrp.info
 version:
  description: Shows the version of the plugin
  usage: /seriousrp version
  permission: seriousrp.info
 help:
  description: Shows the help page
  usage: /seriousrp help
  permission: seriousrp.info
 srtp:
  description: Teleports you randomly in a radius of 10000 blocks
  usage: /srtp
  permission: seriousrp.random
 srtown:
  description: Teleports you to the town
  permission: seriousrp.tptown
 mobile:
  description: Allow you to give a phone
  permission: seriousrp.givephone
 revive:
  description: Allow you to revive a player
  permission: seriousrp.medicrevive
 hrprevive:
  description: Allow you to revive a player HRP
  permission: seriousrp.medichrp
 medinfo:
  description: Allow you to know some info about a player
  permission: seriousrp.medinfo