# SeriousRP | Owner : stan1712 
# Traductors : ErHak_ / legaming04 -> https://github.com/stan1712/SeriousRP/wiki/Translations 
# Our Discord : https://discord.gg/DkQSQa7
Version: VERSION NOT SET PLEASE SET ConfigFix TO true
ConfigFix: true
Prefix: SeriousRP

#Core messages
Core:
  Discord: "Notre discord :"
  NoPerms: "Vous n'avez pas la permission !"
  HelpMsg:
    Help: "Besoin d'aide ? Tapez /seriousrp help"
    VersionHelp: "Version du plugin ? Tapez /seriousrp version"
    DiscordHelp: "Rejoignez notre discord ! /seriousrp discord"
    StatusHelp: "Quels sont les modules activés ? /seriousrp status"
    Dsrtp: "Pouvoir se téléporter aléatoirement"
    DTown: "Permet de se téléporter dans la ville"
    DTownSet: "Permet de définir le point de spawn de la ville"
    DTownWhere: "Permet de savoir où se trouve la ville"
    DPhone: "Affiche le menu du telephone"
    DHelp: "Affiche l'aide"
    DVersion: "Connaitre la version du plugin"
    DStatus: "Affiche l'état des modules"
    DDiscord: "Affiche le lien du discord"
    DRevive: "Réanime et soigne un joueur"
    DMedinfo: "Permet de savoir l'état de santé d'un joueur"
    DHRPRevive: "Vous réanime et vous soigne"
  Modules:
    Error: "Une erreur a ete trouvée ! Regardez la console ainsi que votre fichier config.yml"
    CustomRecipes: true
    RPDeath: true
    Medics: false
    TownSystem: true
    RPMobile: true
    Chairs: true
    
#Modules sections
MicroModules:
  RandomTeleport: "Téléportation a des milliers de blocs !"
  RandomBlocks: 1000
  
Medics:
  Comate: "&cVous êtes dans le coma, appelez les Urgentistes ou faites /hrprevive s'il ne sont pas disponibles"
  MedRevive:
    Revive: "&aVous avez bien réanimé le joueur"
    Self: "&aVous vous êtes bien réanimé"
    Error: "&cn'est pas en ligne ou vous avez mal orthographié son pseudo !"
    NoNeed: "&cLe joueur n'a pas besoin de se faire réanimer"
  MedInfo:
    Health: "Vie :"
    Hearts: "coeurs"
    Food: "Nourriture :"
    Coordinates: "est en :"
    Effects: "Effets"
    
TownSystem:
  Teleports:
    GoToTown: "Vous avez ete téléporte dans la ville"
    SetTown: "Vous avez défini le spawn de la ville"
    TownWhere: "Le spawn de la ville se trouve en :"
  Locations:
    Town:
      x: 0
      y: 0
      z: 0
      WorldName: world
    
RPMobiles:
  LorePhone1: "&9Voici votre telephone"
  LorePhone2: "&9Clic droit pour l'ouvrir"
  LorePhone3: "&6Proprietaire :"
  Answer: "&aDecrocher"
  HangUp: "&cRaccrocher"
  Shutdown: "&cEteindre"
  You: "&aOui, c'est vous, vous etes beau non ?"
  Music: "&cBientot..."
  GoToTown: "&aDirection : Ville"
  YourNumber: "&cBientot..."
  
Chairs:
  - WOOD_STAIRS
  - SPRUCE_WOOD_STAIRS
  - JUNGLE_WOOD_STAIRS
  - BIRCH_WOOD_STAIRS
  - SANDSTONE_STAIRS
  - COBBLESTONE_STAIRS
  - BRICK_STAIRS
  - SMOOTH_STAIRS
  - NETHER_BRICK_STAIRS
  - QUARTZ_STAIRS
  - ACACIA_STAIRS
  - DARK_OAK_STAIRS
  - WOOL
  - STONE_SLAB