name: SeriousRP
description: Free Roleplay Plugin
author: stan1712
version: 3.9.9-3.0g
main: fr.stan1712.seriousrp.Main

commands:
  seriousrp:
    permission: seriousrp.info
  srtp:
    permission: seriousrp.randomtp
  srtown:
    permission: seriousrp.town
  revive:
    permission: seriousrp.medrevive
  hrprevive:
    permission: seriousrp.medhrprevive
  medinfo:
    permission: seriousrp.medinfo
    